image: node:14-alpine

stages:
  - build
  - prepare
  - deploy

cache:
  paths:
    - node_modules/

install-dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

unit-tests:
  stage: prepare
  script: npm test

lint:
  stage: prepare
  script: npm run lint
